import { PDFDocument, PDFPage } from '../types/pdf';

export const ENGLISH_INVOICE_TEMPLATE: PDFPage[] = [
  {
    id: 'p-invoice-en-1',
    pageNumber: 1,
    width: 794,
    height: 1123,
    orientation: 'portrait',
    backgroundColor: '#ffffff',
    elements: [
      // Header Bar
      {
        id: 'shape-inv-bar',
        type: 'rect',
        x: 50,
        y: 50,
        width: 694,
        height: 90,
        zIndex: 1,
        fillColor: '#0f172a',
        strokeColor: '#0f172a',
        strokeWidth: 1,
        borderRadius: 8
      },
      {
        id: 'txt-inv-title',
        type: 'text',
        x: 70,
        y: 70,
        width: 300,
        height: 40,
        zIndex: 2,
        text: 'COMMERCIAL INVOICE',
        fontSize: 22,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'left'
      },
      {
        id: 'txt-inv-no',
        type: 'text',
        x: 480,
        y: 72,
        width: 240,
        height: 30,
        zIndex: 2,
        text: 'Invoice #: #INV-2026-089',
        fontSize: 14,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '600',
        color: '#94a3b8',
        textAlign: 'right'
      },
      // Vendor Details
      {
        id: 'txt-vendor-head',
        type: 'text',
        x: 50,
        y: 160,
        width: 320,
        height: 25,
        zIndex: 3,
        text: 'Issued By: Tech Solutions Global Inc.',
        fontSize: 15,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'left'
      },
      {
        id: 'txt-vendor-sub',
        type: 'text',
        x: 50,
        y: 190,
        width: 320,
        height: 60,
        zIndex: 3,
        text: 'Tax ID / VAT: US-94857200003\n100 Innovation Way, Suite 400, New York, NY\nbilling@techsolutions.com',
        fontSize: 12,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#64748b',
        textAlign: 'left',
        lineHeight: 1.6
      },
      // Client Details
      {
        id: 'txt-client-head',
        type: 'text',
        x: 450,
        y: 160,
        width: 294,
        height: 25,
        zIndex: 3,
        text: 'Billed To (Client):',
        fontSize: 15,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'right'
      },
      {
        id: 'txt-client-sub',
        type: 'text',
        x: 450,
        y: 190,
        width: 294,
        height: 60,
        zIndex: 3,
        text: 'Apex Horizon Consulting LLC\nInvoice Date: Sep 25, 2026\nPayment Due: Oct 15, 2026',
        fontSize: 12,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#64748b',
        textAlign: 'right',
        lineHeight: 1.6
      },
      // Table Header
      {
        id: 'shape-table-head',
        type: 'rect',
        x: 50,
        y: 270,
        width: 694,
        height: 40,
        zIndex: 4,
        fillColor: '#f8fafc',
        strokeColor: '#cbd5e1',
        strokeWidth: 1,
        borderRadius: 4
      },
      {
        id: 'txt-th-item',
        type: 'text',
        x: 70,
        y: 280,
        width: 320,
        height: 24,
        zIndex: 5,
        text: 'Description & Services',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#334155',
        textAlign: 'left'
      },
      {
        id: 'txt-th-qty',
        type: 'text',
        x: 410,
        y: 280,
        width: 70,
        height: 24,
        zIndex: 5,
        text: 'Qty',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'txt-th-rate',
        type: 'text',
        x: 500,
        y: 280,
        width: 100,
        height: 24,
        zIndex: 5,
        text: 'Unit Price',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'txt-th-total',
        type: 'text',
        x: 620,
        y: 280,
        width: 110,
        height: 24,
        zIndex: 5,
        text: 'Total (USD)',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#334155',
        textAlign: 'right'
      },
      // Row 1
      {
        id: 'txt-r1-desc',
        type: 'text',
        x: 70,
        y: 325,
        width: 320,
        height: 35,
        zIndex: 5,
        text: 'Cloud Document Platform Architecture & Engine',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '500',
        color: '#1e293b',
        textAlign: 'left'
      },
      {
        id: 'txt-r1-qty',
        type: 'text',
        x: 410,
        y: 325,
        width: 70,
        height: 35,
        zIndex: 5,
        text: '1',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'txt-r1-rate',
        type: 'text',
        x: 500,
        y: 325,
        width: 100,
        height: 35,
        zIndex: 5,
        text: '$12,500.00',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'txt-r1-tot',
        type: 'text',
        x: 620,
        y: 325,
        width: 110,
        height: 35,
        zIndex: 5,
        text: '$12,500.00',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '600',
        color: '#1e293b',
        textAlign: 'right'
      },
      {
        id: 'line-r1',
        type: 'line',
        x: 50,
        y: 365,
        width: 694,
        height: 1,
        zIndex: 4,
        strokeColor: '#e2e8f0',
        strokeWidth: 1
      },
      // Row 2
      {
        id: 'txt-r2-desc',
        type: 'text',
        x: 70,
        y: 380,
        width: 320,
        height: 35,
        zIndex: 5,
        text: 'Professional Book Publishing & InDesign Layout Setup',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '500',
        color: '#1e293b',
        textAlign: 'left'
      },
      {
        id: 'txt-r2-qty',
        type: 'text',
        x: 410,
        y: 380,
        width: 70,
        height: 35,
        zIndex: 5,
        text: '12',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'txt-r2-rate',
        type: 'text',
        x: 500,
        y: 380,
        width: 100,
        height: 35,
        zIndex: 5,
        text: '$500.00',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'txt-r2-tot',
        type: 'text',
        x: 620,
        y: 380,
        width: 110,
        height: 35,
        zIndex: 5,
        text: '$6,000.00',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '600',
        color: '#1e293b',
        textAlign: 'right'
      },
      {
        id: 'line-r2',
        type: 'line',
        x: 50,
        y: 420,
        width: 694,
        height: 1,
        zIndex: 4,
        strokeColor: '#cbd5e1',
        strokeWidth: 1
      },
      // Totals Card
      {
        id: 'shape-calc-box',
        type: 'rect',
        x: 424,
        y: 450,
        width: 320,
        height: 140,
        zIndex: 4,
        fillColor: '#f8fafc',
        strokeColor: '#e2e8f0',
        strokeWidth: 1,
        borderRadius: 6
      },
      {
        id: 'txt-subtot-lbl',
        type: 'text',
        x: 440,
        y: 465,
        width: 150,
        height: 25,
        zIndex: 5,
        text: 'Subtotal:',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '500',
        color: '#64748b',
        textAlign: 'left'
      },
      {
        id: 'txt-subtot-val',
        type: 'text',
        x: 600,
        y: 465,
        width: 130,
        height: 25,
        zIndex: 5,
        text: '$18,500.00',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '600',
        color: '#1e293b',
        textAlign: 'right'
      },
      {
        id: 'txt-tax-lbl',
        type: 'text',
        x: 440,
        y: 495,
        width: 150,
        height: 25,
        zIndex: 5,
        text: 'Sales Tax / VAT (10%):',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '500',
        color: '#64748b',
        textAlign: 'left'
      },
      {
        id: 'txt-tax-val',
        type: 'text',
        x: 600,
        y: 495,
        width: 130,
        height: 25,
        zIndex: 5,
        text: '$1,850.00',
        fontSize: 13,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '600',
        color: '#1e293b',
        textAlign: 'right'
      },
      {
        id: 'txt-final-lbl',
        type: 'text',
        x: 440,
        y: 535,
        width: 150,
        height: 35,
        zIndex: 5,
        text: 'Total Amount Due:',
        fontSize: 15,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'left'
      },
      {
        id: 'txt-final-val',
        type: 'text',
        x: 600,
        y: 535,
        width: 130,
        height: 35,
        zIndex: 5,
        text: '$20,350.00',
        fontSize: 17,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#dc2626',
        textAlign: 'right'
      },
      // Stamp
      {
        id: 'stamp-inv-paid',
        type: 'stamp',
        x: 70,
        y: 460,
        width: 180,
        height: 80,
        zIndex: 6,
        text: 'PAID IN FULL',
        subtext: 'OFFICIAL RECEIPT',
        color: '#059669',
        shape: 'rectangle',
        date: '2026-09-25',
        rotation: -5
      },
      // Notes & Bank details
      {
        id: 'txt-notes-head',
        type: 'text',
        x: 50,
        y: 630,
        width: 694,
        height: 25,
        zIndex: 4,
        text: 'Payment Instructions & Terms:',
        fontSize: 14,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        color: '#334155',
        textAlign: 'left'
      },
      {
        id: 'txt-notes-body',
        type: 'text',
        x: 50,
        y: 660,
        width: 694,
        height: 60,
        zIndex: 4,
        text: '1. Please remit wire transfers to Swift/BIC: CHASEUS33, Account: 98401928401\n2. Payment terms: Net 30 days upon invoice receipt.\n3. For any billing questions or tax certificates, please contact accounting@techsolutions.com',
        fontSize: 12,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        color: '#64748b',
        textAlign: 'left',
        lineHeight: 1.8
      }
    ]
  }
];
