import { PDFDocument, PDFPage } from '../types/pdf';

export interface TemplateItem {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  description: string;
  thumbnailColor: string;
  pages: PDFPage[];
}

export const TEMPLATES: TemplateItem[] = [
  {
    id: 'blank',
    name: 'مستند فارغ',
    nameEn: 'Blank Document',
    category: 'عام',
    description: 'صفحة بيضاء فارغة للبدء من الصفر بتنسيق A4 القياسي.',
    thumbnailColor: 'bg-white border-dashed',
    pages: [
      {
        id: 'p-1',
        pageNumber: 1,
        width: 794,
        height: 1123,
        orientation: 'portrait',
        backgroundColor: '#ffffff',
        elements: [
          {
            id: 'txt-blank-title',
            type: 'text',
            x: 60,
            y: 70,
            width: 674,
            height: 48,
            zIndex: 1,
            text: 'عنوان المستند الرئيسي',
            fontSize: 28,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right',
            lineHeight: 1.4
          },
          {
            id: 'line-blank-div',
            type: 'line',
            x: 60,
            y: 125,
            width: 674,
            height: 2,
            zIndex: 2,
            strokeColor: '#e2e8f0',
            strokeWidth: 2,
            borderStyle: 'solid'
          },
          {
            id: 'txt-blank-body',
            type: 'text',
            x: 60,
            y: 150,
            width: 674,
            height: 120,
            zIndex: 3,
            text: 'انقر هنا مرتين للبدء في كتابة محتوى المستند. يمكنك إضافة نصوص إضافية، صور، توقيع رقمي، وأشكال هندسية من شريط الأدوات العلوي بسهولة تامة.',
            fontSize: 16,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.8
          }
        ]
      }
    ]
  },
  {
    id: 'invoice',
    name: 'فاتورة ضريبية رسمية',
    nameEn: 'Tax & Sales Invoice',
    category: 'أعمال',
    description: 'فاتورة أنيقة وشاملة لبيانات العميل، جدول المنتجات، الحسابات والضريبة، وخاتم الاعتماد.',
    thumbnailColor: 'bg-slate-50',
    pages: [
      {
        id: 'p-invoice-1',
        pageNumber: 1,
        width: 794,
        height: 1123,
        orientation: 'portrait',
        backgroundColor: '#ffffff',
        elements: [
          // Header Bar
          {
            id: 'shape-inv-bar',
            type: 'rect',
            x: 50,
            y: 50,
            width: 694,
            height: 90,
            zIndex: 1,
            fillColor: '#0f172a',
            strokeColor: '#0f172a',
            strokeWidth: 1,
            borderRadius: 8
          },
          {
            id: 'txt-inv-title',
            type: 'text',
            x: 70,
            y: 70,
            width: 300,
            height: 40,
            zIndex: 2,
            text: 'فاتورة ضريبية معتمدة',
            fontSize: 24,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#ffffff',
            textAlign: 'right'
          },
          {
            id: 'txt-inv-no',
            type: 'text',
            x: 480,
            y: 72,
            width: 240,
            height: 30,
            zIndex: 2,
            text: 'رقم الفاتورة: #INV-2026-089',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#94a3b8',
            textAlign: 'left'
          },
          // Vendor Details
          {
            id: 'txt-vendor-head',
            type: 'text',
            x: 450,
            y: 160,
            width: 294,
            height: 25,
            zIndex: 3,
            text: 'صادرة عن شركة التقنية المتقدمة',
            fontSize: 16,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-vendor-sub',
            type: 'text',
            x: 450,
            y: 190,
            width: 294,
            height: 60,
            zIndex: 3,
            text: 'الرقم الضريبي: 31094857200003\nطريق الملك فهد، الرياض، المملكة العربية السعودية\nsupport@techcompany.sa',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#64748b',
            textAlign: 'right',
            lineHeight: 1.6
          },
          // Client Details
          {
            id: 'txt-client-head',
            type: 'text',
            x: 50,
            y: 160,
            width: 294,
            height: 25,
            zIndex: 3,
            text: 'بيانات العميل / السادة:',
            fontSize: 16,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-client-sub',
            type: 'text',
            x: 50,
            y: 190,
            width: 294,
            height: 60,
            zIndex: 3,
            text: 'مؤسسة الأفق للاستشارات وتطوير الأعمال\nالتاريخ: 2026-09-24\nتاريخ الاستحقاق: 2026-10-15',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#64748b',
            textAlign: 'right',
            lineHeight: 1.6
          },
          // Table Header
          {
            id: 'shape-table-head',
            type: 'rect',
            x: 50,
            y: 270,
            width: 694,
            height: 40,
            zIndex: 4,
            fillColor: '#f8fafc',
            strokeColor: '#cbd5e1',
            strokeWidth: 1,
            borderRadius: 4
          },
          {
            id: 'txt-th-item',
            type: 'text',
            x: 450,
            y: 280,
            width: 270,
            height: 24,
            zIndex: 5,
            text: 'الوصف والخدمة',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#334155',
            textAlign: 'right'
          },
          {
            id: 'txt-th-qty',
            type: 'text',
            x: 350,
            y: 280,
            width: 80,
            height: 24,
            zIndex: 5,
            text: 'الكمية',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#334155',
            textAlign: 'center'
          },
          {
            id: 'txt-th-rate',
            type: 'text',
            x: 210,
            y: 280,
            width: 120,
            height: 24,
            zIndex: 5,
            text: 'السعر الفردي',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#334155',
            textAlign: 'center'
          },
          {
            id: 'txt-th-total',
            type: 'text',
            x: 70,
            y: 280,
            width: 120,
            height: 24,
            zIndex: 5,
            text: 'الإجمالي (ر.س)',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#334155',
            textAlign: 'left'
          },
          // Row 1
          {
            id: 'txt-r1-desc',
            type: 'text',
            x: 450,
            y: 325,
            width: 270,
            height: 35,
            zIndex: 5,
            text: 'تطوير منصة إدارة المستندات السحابية',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#1e293b',
            textAlign: 'right'
          },
          {
            id: 'txt-r1-qty',
            type: 'text',
            x: 350,
            y: 325,
            width: 80,
            height: 35,
            zIndex: 5,
            text: '1',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'center'
          },
          {
            id: 'txt-r1-rate',
            type: 'text',
            x: 210,
            y: 325,
            width: 120,
            height: 35,
            zIndex: 5,
            text: '12,500 ر.س',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'center'
          },
          {
            id: 'txt-r1-tot',
            type: 'text',
            x: 70,
            y: 325,
            width: 120,
            height: 35,
            zIndex: 5,
            text: '12,500 ر.س',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'left'
          },
          {
            id: 'line-r1',
            type: 'line',
            x: 50,
            y: 365,
            width: 694,
            height: 1,
            zIndex: 4,
            strokeColor: '#f1f5f9',
            strokeWidth: 1
          },
          // Row 2
          {
            id: 'txt-r2-desc',
            type: 'text',
            x: 450,
            y: 380,
            width: 270,
            height: 35,
            zIndex: 5,
            text: 'خدمات التكامل والدعم الفني السنوي',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#1e293b',
            textAlign: 'right'
          },
          {
            id: 'txt-r2-qty',
            type: 'text',
            x: 350,
            y: 380,
            width: 80,
            height: 35,
            zIndex: 5,
            text: '12 شهر',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'center'
          },
          {
            id: 'txt-r2-rate',
            type: 'text',
            x: 210,
            y: 380,
            width: 120,
            height: 35,
            zIndex: 5,
            text: '500 ر.س',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'center'
          },
          {
            id: 'txt-r2-tot',
            type: 'text',
            x: 70,
            y: 380,
            width: 120,
            height: 35,
            zIndex: 5,
            text: '6,000 ر.س',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'left'
          },
          {
            id: 'line-r2',
            type: 'line',
            x: 50,
            y: 420,
            width: 694,
            height: 1,
            zIndex: 4,
            strokeColor: '#cbd5e1',
            strokeWidth: 1
          },
          // Totals Card
          {
            id: 'shape-calc-box',
            type: 'rect',
            x: 50,
            y: 450,
            width: 320,
            height: 140,
            zIndex: 4,
            fillColor: '#f8fafc',
            strokeColor: '#e2e8f0',
            strokeWidth: 1,
            borderRadius: 6
          },
          {
            id: 'txt-subtot-lbl',
            type: 'text',
            x: 200,
            y: 465,
            width: 150,
            height: 25,
            zIndex: 5,
            text: 'المجموع الفرعي:',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#64748b',
            textAlign: 'right'
          },
          {
            id: 'txt-subtot-val',
            type: 'text',
            x: 70,
            y: 465,
            width: 120,
            height: 25,
            zIndex: 5,
            text: '18,500 ر.س',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'left'
          },
          {
            id: 'txt-tax-lbl',
            type: 'text',
            x: 200,
            y: 495,
            width: 150,
            height: 25,
            zIndex: 5,
            text: 'ضريبة القيمة المضافة (15%):',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#64748b',
            textAlign: 'right'
          },
          {
            id: 'txt-tax-val',
            type: 'text',
            x: 70,
            y: 495,
            width: 120,
            height: 25,
            zIndex: 5,
            text: '2,775 ر.س',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'left'
          },
          {
            id: 'txt-final-lbl',
            type: 'text',
            x: 200,
            y: 535,
            width: 150,
            height: 35,
            zIndex: 5,
            text: 'الإجمالي النهائي:',
            fontSize: 15,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-final-val',
            type: 'text',
            x: 70,
            y: 535,
            width: 120,
            height: 35,
            zIndex: 5,
            text: '21,275 ر.س',
            fontSize: 17,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#dc2626',
            textAlign: 'left'
          },
          // Stamp
          {
            id: 'stamp-inv-paid',
            type: 'stamp',
            x: 520,
            y: 460,
            width: 180,
            height: 80,
            zIndex: 6,
            text: 'تم السداد بالكامل',
            subtext: 'PAID IN FULL',
            color: '#059669',
            shape: 'rectangle',
            date: '2026-09-24',
            rotation: -5
          },
          // Notes & Bank details
          {
            id: 'txt-notes-head',
            type: 'text',
            x: 50,
            y: 630,
            width: 694,
            height: 25,
            zIndex: 4,
            text: 'تعليمات الدفع والشروط:',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#334155',
            textAlign: 'right'
          },
          {
            id: 'txt-notes-body',
            type: 'text',
            x: 50,
            y: 660,
            width: 694,
            height: 60,
            zIndex: 4,
            text: '1. يُرجى تحويل المبالغ لحساب الآيبان البنكي: SA0380000000608010167520\n2. يُعتبر هذا المستند إشعارًا رسميًا بالمطالبة المالية وفقًا للأنظمة المعمول بها.\n3. للاستفسارات المحاسبية يُرجى التواصل عبر billing@techcompany.sa',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#64748b',
            textAlign: 'right',
            lineHeight: 1.8
          }
        ]
      }
    ]
  },
  {
    id: 'contract',
    name: 'عقد اتفاقية وشراكة',
    nameEn: 'Agreement Contract',
    category: 'قانوني',
    description: 'وثيقة قانونية رسمية منظمة لبنود وشروط الاتفاق مع أماكن مخصصة لتوقيع الطرفين.',
    thumbnailColor: 'bg-indigo-50',
    pages: [
      {
        id: 'p-contract-1',
        pageNumber: 1,
        width: 794,
        height: 1123,
        orientation: 'portrait',
        backgroundColor: '#ffffff',
        elements: [
          {
            id: 'txt-c-title',
            type: 'text',
            x: 100,
            y: 60,
            width: 594,
            height: 45,
            zIndex: 1,
            text: 'عقد تقديم خدمات استشارية وتقنية',
            fontSize: 24,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'center'
          },
          {
            id: 'txt-c-sub',
            type: 'text',
            x: 100,
            y: 105,
            width: 594,
            height: 25,
            zIndex: 2,
            text: 'بتاريخ 2026/09/24م، تم إبرام هذا الاتفاق والتراضي بين كلٍ من:',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#64748b',
            textAlign: 'center'
          },
          {
            id: 'line-c-head',
            type: 'line',
            x: 80,
            y: 140,
            width: 634,
            height: 2,
            zIndex: 2,
            strokeColor: '#cbd5e1',
            strokeWidth: 1
          },
          // Parties
          {
            id: 'txt-c-p1',
            type: 'text',
            x: 80,
            y: 160,
            width: 634,
            height: 50,
            zIndex: 3,
            text: 'الطرف الأول: شركة المسار الرقمي للحلول البرمجية، سجل تجاري (1010892341)، ويمثلها في التوقيع المدير التنفيذي.',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'right',
            lineHeight: 1.6
          },
          {
            id: 'txt-c-p2',
            type: 'text',
            x: 80,
            y: 220,
            width: 634,
            height: 50,
            zIndex: 3,
            text: 'الطرف الثاني: مؤسسة النجاح المستدام للتقنية، سجل تجاري (1010774920)، ويمثلها في التوقيع المفوض الرسمي.',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'right',
            lineHeight: 1.6
          },
          // Clauses
          {
            id: 'txt-c-clause1-title',
            type: 'text',
            x: 80,
            y: 285,
            width: 634,
            height: 25,
            zIndex: 3,
            text: 'البند الأول: موضوع العقد ونطاق العمل',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-c-clause1-body',
            type: 'text',
            x: 80,
            y: 315,
            width: 634,
            height: 60,
            zIndex: 3,
            text: 'يقوم الطرف الأول بتقديم خدمات التصميم، البرمجة، وفحص الجودة للأنظمة الرقمية الخاصة بالطرف الثاني، وفقاً لمواصفات ملحق العمل الفني المعتمد والمرفق بهذا العقد.',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.8
          },
          {
            id: 'txt-c-clause2-title',
            type: 'text',
            x: 80,
            y: 390,
            width: 634,
            height: 25,
            zIndex: 3,
            text: 'البند الثاني: مدة العقد والتسليم',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-c-clause2-body',
            type: 'text',
            x: 80,
            y: 420,
            width: 634,
            height: 60,
            zIndex: 3,
            text: 'تسري هذه الاتفاقية لمدة 12 شهراً تبدأ من تاريخ توقيع هذا العقد وتتجدد تلقائياً ما لم يُخطر أحد الطرفين الآخر برغبته في عدم التجديد خطياً قبل 30 يوماً.',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.8
          },
          {
            id: 'txt-c-clause3-title',
            type: 'text',
            x: 80,
            y: 495,
            width: 634,
            height: 25,
            zIndex: 3,
            text: 'البند الثالث: السرية وحفظ البيانات (NDA)',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-c-clause3-body',
            type: 'text',
            x: 80,
            y: 525,
            width: 634,
            height: 60,
            zIndex: 3,
            text: 'يلتزم الطرفان بالحفاظ على سرية كافة البيانات والمستندات التقنية والتجارية المتبادلة وعدم إفشائها لأي طرف ثالث دون موافقة كتابية مسبقة.',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.8
          },
          // Signatures Section
          {
            id: 'shape-sig-div',
            type: 'rect',
            x: 80,
            y: 630,
            width: 634,
            height: 180,
            zIndex: 2,
            fillColor: '#f8fafc',
            strokeColor: '#e2e8f0',
            strokeWidth: 1,
            borderRadius: 8
          },
          {
            id: 'txt-sig-p1-title',
            type: 'text',
            x: 430,
            y: 650,
            width: 250,
            height: 25,
            zIndex: 4,
            text: 'توقيع واعتماد الطرف الأول:',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-sig-p1-name',
            type: 'text',
            x: 430,
            y: 680,
            width: 250,
            height: 40,
            zIndex: 4,
            text: 'الاسم: د. خالد السليمان\nالصفة: الرئيس التنفيذي',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#64748b',
            textAlign: 'right',
            lineHeight: 1.6
          },
          {
            id: 'txt-sig-p2-title',
            type: 'text',
            x: 110,
            y: 650,
            width: 250,
            height: 25,
            zIndex: 4,
            text: 'توقيع واعتماد الطرف الثاني:',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-sig-p2-name',
            type: 'text',
            x: 110,
            y: 680,
            width: 250,
            height: 40,
            zIndex: 4,
            text: 'الاسم: م. عبد الرحمن العتيبي\nالصفة: المدير العام المفوض',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#64748b',
            textAlign: 'right',
            lineHeight: 1.6
          },
          // Official Stamp
          {
            id: 'stamp-contract',
            type: 'stamp',
            x: 300,
            y: 710,
            width: 170,
            height: 75,
            zIndex: 6,
            text: 'مُعتمد رسميًا',
            subtext: 'OFFICIALLY RATIFIED',
            color: '#15803d',
            shape: 'rectangle',
            date: '2026-09-24',
            rotation: 2
          }
        ]
      }
    ]
  },
  {
    id: 'resume',
    name: 'سيرة ذاتية احترافية (CV)',
    nameEn: 'Modern Executive Resume',
    category: 'شخصي',
    description: 'قالب سيرة ذاتية عصري مع عمود جانبي للمهارات والاتصال وأقسام الخبرات والتعليم.',
    thumbnailColor: 'bg-emerald-50',
    pages: [
      {
        id: 'p-cv-1',
        pageNumber: 1,
        width: 794,
        height: 1123,
        orientation: 'portrait',
        backgroundColor: '#ffffff',
        elements: [
          // Sidebar Background
          {
            id: 'shape-cv-side',
            type: 'rect',
            x: 520,
            y: 0,
            width: 274,
            height: 1123,
            zIndex: 1,
            fillColor: '#0f172a',
            strokeColor: '#0f172a',
            strokeWidth: 0
          },
          // Sidebar Content
          {
            id: 'txt-cv-side-name',
            type: 'text',
            x: 540,
            y: 80,
            width: 234,
            height: 40,
            zIndex: 2,
            text: 'م. أحمد الراشد',
            fontSize: 22,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#ffffff',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-side-role',
            type: 'text',
            x: 540,
            y: 125,
            width: 234,
            height: 30,
            zIndex: 2,
            text: 'مهندس برمجيات ونظم سحابية',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#38bdf8',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-contact-h',
            type: 'text',
            x: 540,
            y: 190,
            width: 234,
            height: 25,
            zIndex: 2,
            text: 'معلومات الاتصال',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#f8fafc',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-contact-b',
            type: 'text',
            x: 540,
            y: 220,
            width: 234,
            height: 100,
            zIndex: 2,
            text: 'الهاتف: +966 55 123 4567\nالبريد: ahmad@alrashed.dev\nالرياض، المملكة العربية السعودية\nlinkedin.com/in/alrashed',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#94a3b8',
            textAlign: 'right',
            lineHeight: 1.8
          },
          {
            id: 'txt-cv-skills-h',
            type: 'text',
            x: 540,
            y: 350,
            width: 234,
            height: 25,
            zIndex: 2,
            text: 'المهارات التقنية',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#f8fafc',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-skills-b',
            type: 'text',
            x: 540,
            y: 380,
            width: 234,
            height: 180,
            zIndex: 2,
            text: '• هندسة النظم السحابية (GCP / AWS)\n• تطوير React و Next.js و TypeScript\n• قواعد البيانات PostgreSQL و Redis\n• أمن المعلومات وهندسة المعمارية\n• إدارة المنتجات Agile & Scrum',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#cbd5e1',
            textAlign: 'right',
            lineHeight: 1.9
          },
          // Main Body
          {
            id: 'txt-cv-summary-h',
            type: 'text',
            x: 50,
            y: 70,
            width: 440,
            height: 30,
            zIndex: 2,
            text: 'الملخص المهني',
            fontSize: 18,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-summary-b',
            type: 'text',
            x: 50,
            y: 105,
            width: 440,
            height: 70,
            zIndex: 2,
            text: 'مهندس برمجيات بخبرة تزيد عن 8 سنوات في قيادة الفرق التقنية وبناء المنصات الرقمية السحابية واسعة النطاق. شغوف بابتكار حلول سهلة الاستخدام وذات موثوقية عالية.',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.7
          },
          {
            id: 'line-cv-div1',
            type: 'line',
            x: 50,
            y: 190,
            width: 440,
            height: 1,
            zIndex: 2,
            strokeColor: '#e2e8f0',
            strokeWidth: 1
          },
          {
            id: 'txt-cv-exp-h',
            type: 'text',
            x: 50,
            y: 210,
            width: 440,
            height: 30,
            zIndex: 2,
            text: 'الخبرات المهنية',
            fontSize: 18,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-exp1-h',
            type: 'text',
            x: 50,
            y: 245,
            width: 440,
            height: 25,
            zIndex: 2,
            text: 'كبير مهندسي البرمجيات | شركة سحاب للتقنية (2022 - حتى الآن)',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#1e293b',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-exp1-b',
            type: 'text',
            x: 50,
            y: 275,
            width: 440,
            height: 75,
            zIndex: 2,
            text: '• قيادة فريق مكون من 10 مطورين لبناء منصة مستندات رقمية.\n• تحسين أداء استجابة الأنظمة بنسبة 45% وتوسيع قاعدة المستخدمين.\n• الإشراف على معايير الأمان والتوافق مع شهادات ISO.',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.8
          },
          {
            id: 'txt-cv-exp2-h',
            type: 'text',
            x: 50,
            y: 360,
            width: 440,
            height: 25,
            zIndex: 2,
            text: 'مطور واجهات ومستشار تقني | أفق ديجيتال (2018 - 2022)',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#1e293b',
            textAlign: 'right'
          },
          {
            id: 'txt-cv-exp2-b',
            type: 'text',
            x: 50,
            y: 390,
            width: 440,
            height: 70,
            zIndex: 2,
            text: '• تطوير تطبيقات الويب الحديثة وتصميم تجارب مستخدم مميزة.\n• الربط مع بوابات الدفع الإلكتروني وخدمات التحقق الآمن.',
            fontSize: 12,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#475569',
            textAlign: 'right',
            lineHeight: 1.8
          }
        ]
      }
    ]
  },
  {
    id: 'certificate',
    name: 'شهادة تقدير وإنجاز',
    nameEn: 'Certificate of Appreciation',
    category: 'تعليم',
    description: 'شهادة تكريم فاخرة بإطار ملكي وزخارف، مناسبة للدورات والإنجازات المهنية.',
    thumbnailColor: 'bg-amber-50',
    pages: [
      {
        id: 'p-cert-1',
        pageNumber: 1,
        width: 794,
        height: 1123,
        orientation: 'portrait',
        backgroundColor: '#ffffff',
        elements: [
          // Outer Border Frame
          {
            id: 'shape-cert-frame',
            type: 'rect',
            x: 40,
            y: 40,
            width: 714,
            height: 1043,
            zIndex: 1,
            fillColor: 'transparent',
            strokeColor: '#b45309', // amber-700
            strokeWidth: 4,
            borderRadius: 12
          },
          {
            id: 'shape-cert-inner-frame',
            type: 'rect',
            x: 50,
            y: 50,
            width: 694,
            height: 1023,
            zIndex: 1,
            fillColor: 'transparent',
            strokeColor: '#fde68a', // amber-200
            strokeWidth: 1,
            borderRadius: 8
          },
          // Header
          {
            id: 'txt-cert-org',
            type: 'text',
            x: 80,
            y: 100,
            width: 634,
            height: 30,
            zIndex: 2,
            text: 'أكاديمية التميز والإبداع المهني',
            fontSize: 16,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#92400e',
            textAlign: 'center'
          },
          {
            id: 'txt-cert-main',
            type: 'text',
            x: 80,
            y: 160,
            width: 634,
            height: 60,
            zIndex: 2,
            text: 'شـهـادة تـقـديـر وتـمـيـز',
            fontSize: 34,
            fontFamily: 'Cairo',
            fontWeight: '800',
            color: '#78350f',
            textAlign: 'center'
          },
          {
            id: 'txt-cert-grant',
            type: 'text',
            x: 80,
            y: 240,
            width: 634,
            height: 30,
            zIndex: 2,
            text: 'يُسعدنا منح هذه الشهادة بكل فخر واعتزاز إلى:',
            fontSize: 15,
            fontFamily: 'Cairo',
            fontWeight: 'normal',
            color: '#64748b',
            textAlign: 'center'
          },
          {
            id: 'txt-cert-recipient',
            type: 'text',
            x: 80,
            y: 290,
            width: 634,
            height: 50,
            zIndex: 2,
            text: 'المهندس / عبد الله المنصور',
            fontSize: 28,
            fontFamily: 'Cairo',
            fontWeight: 'bold',
            color: '#0f172a',
            textAlign: 'center'
          },
          {
            id: 'line-cert-decor',
            type: 'line',
            x: 240,
            y: 350,
            width: 314,
            height: 2,
            zIndex: 2,
            strokeColor: '#d97706',
            strokeWidth: 2
          },
          {
            id: 'txt-cert-desc',
            type: 'text',
            x: 100,
            y: 380,
            width: 594,
            height: 80,
            zIndex: 2,
            text: 'تقديراً لإتمامه بنجاح البرنامج الاحترافي المتقدم في:\n"هندسة وإدارة المستندات الرقمية الذكية"\nبمعدل امتياز مع مرتبة الشرف الأولى وبمجموع 60 ساعة تدريبية معتمدة.',
            fontSize: 14,
            fontFamily: 'Cairo',
            fontWeight: '500',
            color: '#334155',
            textAlign: 'center',
            lineHeight: 1.9
          },
          // Seal / Stamp
          {
            id: 'stamp-cert-seal',
            type: 'stamp',
            x: 310,
            y: 520,
            width: 174,
            height: 85,
            zIndex: 5,
            text: 'نسخة طبق الأصل',
            subtext: 'OFFICIAL ACCREDITED',
            color: '#b45309',
            shape: 'oval',
            date: '2026-09-24',
            rotation: 0
          },
          // Signatures
          {
            id: 'txt-cert-sig1',
            type: 'text',
            x: 480,
            y: 680,
            width: 200,
            height: 50,
            zIndex: 3,
            text: 'رئيس مجلس الإدارة\nد. فهد القحطاني',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'center',
            lineHeight: 1.6
          },
          {
            id: 'txt-cert-sig2',
            type: 'text',
            x: 110,
            y: 680,
            width: 200,
            height: 50,
            zIndex: 3,
            text: 'مدير عام التدريب والتطوير\nأ. منى الشمري',
            fontSize: 13,
            fontFamily: 'Cairo',
            fontWeight: '600',
            color: '#1e293b',
            textAlign: 'center',
            lineHeight: 1.6
          }
        ]
      }
    ]
  }
];
